"use client";
import { useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ExplanationSelector from "@/components/ExplanationSelector";
import { mockPolicies } from "@/lib/data/mock";
import { ExplanationLevel,Policy } from "@/lib/types";

export default function PolicyDetail(){const params=useParams<{id:string}>(); const router=useRouter(); const [policy,setPolicy]=useState<Policy|undefined>(()=>mockPolicies.find(p=>p.id===params.id)); const [fetching,setFetching]=useState(!policy); const [level,setLevel]=useState<ExplanationLevel>("easy"); const [style,setStyle]=useState("정보형 블로그"); const [loading,setLoading]=useState(false); useEffect(()=>{fetch(`/api/policies/${encodeURIComponent(params.id)}`).then(r=>r.json()).then(d=>{if(d.policy)setPolicy(d.policy)}).finally(()=>setFetching(false))},[params.id]); if(fetching)return <><Header/><main className="container"><div className="empty">정책 정보를 불러오는 중...</div></main></>; if(!policy)return <><Header/><main className="container"><div className="empty">정책을 찾을 수 없습니다.</div></main></>;
 async function generate(){if(!policy)return; const currentPolicy=policy; setLoading(true); sessionStorage.removeItem("generation-error"); try{const res=await fetch("/api/rag/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({policyId:currentPolicy.id,policyTitle:currentPolicy.title,level,style})}); const data=await res.json(); if(!res.ok){sessionStorage.setItem("generation-error",data.error??"RAG 생성에 실패했습니다."); alert(data.error??"RAG 생성에 실패했습니다."); return;} sessionStorage.setItem("generated-article",JSON.stringify(data.article)); sessionStorage.setItem("generated-policy",JSON.stringify(currentPolicy)); sessionStorage.setItem("generated-level",level); sessionStorage.setItem("generated-style",style); localStorage.setItem("generated-article",JSON.stringify(data.article)); localStorage.setItem("generated-policy",JSON.stringify(currentPolicy)); localStorage.setItem("generated-level",level); localStorage.setItem("generated-style",style); router.push(`/articles/${encodeURIComponent(currentPolicy.id)}`);}finally{setLoading(false)}}
 return <><Header active="search"/><main className="container"><div className="page-header"><div><span className="badge soft">{policy.category}</span><h1 style={{marginTop:10}}>{policy.title}</h1><p>{policy.shortDescription}</p></div></div><div className="two-col"><section className="panel"><h2>정책 분석</h2><div className="policy-meta"><span className="badge soft">{policy.agency}</span><span className="muted small">자료 최종 확인: {policy.lastVerifiedAt??"확인 필요"}</span></div><div className="info-list"><div className="info-row"><b>정책 목적</b><p>{policy.purpose??"공식 정책 문서를 연결하면 RAG 분석으로 채워집니다."}</p></div><div className="info-row"><b>지원 대상</b><p>{policy.eligibility?.join(" · ")??"공식 정책 문서를 연결하면 RAG 분석으로 채워집니다."}</p></div><div className="info-row"><b>지원 내용</b><p>{policy.benefits?.join(" · ")??"공식 정책 문서를 연결하면 RAG 분석으로 채워집니다."}</p></div><div className="info-row"><b>신청 기간</b><p>{policy.applicationPeriod??"공식 정책 문서 연결 후 표시됩니다."}</p></div><div className="info-row"><b>신청 방법</b><p>{policy.applicationMethod?.join(" · ")??"공식 정책 문서 연결 후 표시됩니다."}</p></div></div></section><aside className="panel"><h2>어떻게 설명해드릴까요?</h2><ExplanationSelector value={level} onChange={setLevel}/><div className="divider"/><div className="settings-row"><div><label>글 스타일</label><select value={style} onChange={e=>setStyle(e.target.value)}><option>친근한 설명</option><option>정보형 블로그</option><option>질문과 답변형</option></select></div><div><label>설명 수준</label><select value={level} onChange={e=>setLevel(e.target.value as ExplanationLevel)}><option value="quick">한눈에</option><option value="easy">쉽게</option><option value="detailed">상세하게</option></select></div></div><div className="divider"/><button className="btn primary wide large" onClick={generate} disabled={loading}>{loading?<span className="loading"><span className="spinner"/>공식 근거 검색 중...</span>:"설명 글 만들기"}</button><div className="helper">정책의 조건과 사실은 그대로 유지하고 설명 방식만 변경합니다.</div></aside></div></main><Footer/></>}
